---
defaults:
  - strategy: fedavg

num_clients: 1000 # total number of clients
num_epochs: 10 # number of local epochs
batch_size: 10
num_rounds: 100
clients_per_round: 10
iid: False
balance: True
learning_rate: 0.03
stragglers_fraction: 0.9
mu: 0.0 # it should be zero always if not using FedProx
save_path: "docs/results"

# in FedAvg, stragglers should be dropped. So we tell clients FedAvg is being used
# by passing flag `drop_client`=True
fit_config:
  proximal_mu: ${mu}
  drop_client: true

model:
  _target_: flwr_baselines.publications.fedprox_mnist.model.LogisticRegression
  num_classes: 10
