_target_: strategy.FedAvgWithStragglerDrop
fraction_fit: 0.00001 # because we want the number of clients to sample on each roudn to be solely defined by min_fit_clients
fraction_evaluate: 0.0
min_fit_clients: ${clients_per_round}
min_available_clients: ${clients_per_round}
min_evaluate_clients: 0